import { sign, verify } from "jsonwebtoken";
const JWT_SECRET = process.env.JWT_SECRET || "token.01010101";

//This utility is useful for managing the tokens generated by JWT.

// Generates the application access token.
const generateToken = (id: string) => {
	const jwt = sign({ id }, JWT_SECRET, {
		expiresIn: "2h",
	});
	return jwt;
};

// Verify that the token is valid.
const verifyToken = (jwt: string) => {
	const isOk = verify(jwt, JWT_SECRET);
	return isOk;
};

export { generateToken, verifyToken };
